// SURVEYS
export const GET_SURVEYS_IN_PROGRESS = 'GET_SURVEYS_IN_PROGRESS';
export const SET_SURVEYS = 'SET_SURVEYS';
export const SET_SURVEYS_FAILED = 'SET_SURVEYS_FAILED';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';

// SURVEY DETAILS
export const GET_SURVEY_DETAILS_IN_PROGRESS = 'GET_SURVEY_DETAILS_IN_PROGRESS';
export const SET_SURVEY_DETAILS = 'SET_SURVEY_DETAILS';
export const SET_SURVEY_DETAILS_FAILED = 'SET_SURVEY_DETAILS_FAILED';
export const GET_SURVEY_DETAILS_SUCCESS = 'GET_SURVEY_DETAILS_SUCCESS';
